### ISSUE TITLE
Unable To Save New Cheats

### ISSUE THREAD

**Issue by SophieBaybey** [vitor251093/KHDays_FM#104]
I was hoping to make a sort of homebrew Critical mode using action replay codes and this emulator, but I'm not able to save any new cheats. I assume this probably has something to do with the ones that are built in already. Would it be possible to be able to save new cheats with Melon Mix?

**Comment by sandwichwater** [comment]
its not recommended , but in the .ini file make sure "CheatFilePath=" is pointed towards another path . this should override the cheats melon mix ships with but will let you use whatever action replay codes you want

as for the critical mode if youre ever willing to share your codes we could probably add them and have a checkbox when launching the game to enable critical mode for the people who want it

**Comment by vitor251093** [comment]
Just clarifying one thing: we use the method described by @sandwichwater so we can change the built in cheats without having to deal with older versions of those cheats causing issues. We may add an option at the UI in the future to make this process easier (something like "Cheats Mode" => "Built in Cheats only" / "Merge with Custom Cheats" / "Replace with Custom Cheats"), but it will have a low priority, since it isn't the main focus right now.

**Comment by vitor251093** [comment]
Fixed
