### ISSUE TITLE
Windows build crashing on launch

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#11]

**Comment by CpazR** [comment]
Can also confirm that, after building on msys2, this is still crashing. Swapping to the software renderer through the .ini didn't seem to make a difference either.

Does MelonDS have any sort of debug logging? Would probably be useful if I could attach a log file or something.

**Comment by sandwichwater** [comment]
i dont know about debug logging but apparently the issue is caused due to the melon devs revamping the opengl engine earlier this year//late last year . which now is even more confusing that not even the software renderer is working . something definitely weird is going on if og melonds works on windows but not this modified version , maybe theres a line or more of code that does work on linux but causes a crash on windows due to it not knowing how to handle it ¿ again , not a programmer , but i think theres a chance if its happening on only windows but working fine on linux

**Comment by vitor251093** [comment]
I tried changing the default value and testing it in a Windows VM. No change. Same issue.

> Does MelonDS have any sort of debug logging? Would probably be useful if I could attach a log file or something.

```
khDaysMM 0.1.0
https://github.com/vitor251093/KHDays_FM
IPC sharedmem doesn't exist. creating
IPC: instance ID 0
Audio output frequency: 48000 Hz
Loading GLAD WGL functions failed

./build.ps1: line 4:   148 Segmentation fault      ./khDaysMM.exe
```

**Comment by sandwichwater** [comment]
i may be wrong but glad is a version of opengl isnt it ¿

https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#glad_(Multi-Language_GL/GLES/EGL/GLX/WGL_Loader-Generator)

and if thats really not the issue then i guess we need to figure out whats causing the segmentation fault in C , i did a bit of looking and its either due to the index thats used to access the array being outside the bounds of the array , or having the same block of memory being freed twice . i dont exactly understand it but maybe its of more help to you ¿

**Comment by vitor251093** [comment]
Well, it does fail to load "GLAD WGL functions", and at this point, the Linux binary prints "Created a OpenGL context" instead.

**Comment by sandwichwater** [comment]
odd , interesting too that building natively on windows causes it to fail too as both me and the other person in these comments get the same issue when building natively on windows as opposed to the prebuilt . ill look into it more and examine the changes again , but nothing stood out to me as causing it to fail so im pretty stumped too

**Comment by sandwichwater** [comment]
hey the latest build seems to launch the emulator ! congrats , ill test to make sure everything works and report back in a bit

**Comment by vitor251093** [comment]
The worked in your computer? They didn't work in my VM :/

I just commited another change, trying to make it work there.

**Comment by vitor251093** [comment]
Ok, now I discovered it! That commit fixed the issue:
https://github.com/vitor251093/KHDays_FM/commit/af0d1b432f5bb81bc1e348532a466fba2bb44428

The problem is: VirtualBox can't run even melonDS's OpenGL renderer, so it was crashing anyway. I will move the fixes to the master branch.

**Comment by sandwichwater** [comment]
ahhh that makes sense , good to know the issue has finally been solved after all this time🎉 ill make sure to report any bugs i find

**Comment by vitor251093** [comment]
> good to know the issue has finally been solved after all this time

It sure is :D I will close this issue, considering the problem is solved.

> ill make sure to report any bugs i find

Thank you!
