### ISSUE TITLE
Less of an issue, more of a question: does anyone know about modding enemy stats or missions? Where would one get started with making AR codes that branch off of what this project does?

### ISSUE THREAD

**Issue by TOYSIPO** [vitor251093/KHDays_FM#117]
This is probably outside the scope of this project, but I can't think of anywhere better to toss this question:

Has anyone put any amount of research into changing enemy stats? Either by changing variables in the Mission Mode options menu, or on a per-mission or per-enemy basis? Mission Mode allegedly being balanced for a full 4-player party is kind of ridiculous when the 1P balancing is actually okay for the most part. Maybe there's a simple value or flag in mission mode that causes this horrendous scaling to take effect.

It'd be crazy if we could do even more to the game, but I know how impossible and unheard of it is to actually decompile an nds rom. I think, if we could just use an AR code to change the flags or values for the Mission Mode modifiers, we'd be in a good spot.

I might get to work trying to create a code which plays with the values you can find in the Mission Mode options myself-- there's two noteworthy ones, one affecting enemy damage output and the other player damage output. I'm interested to see if I can do a simple variable swap with AR for the player damage value. All the options are, hilariously enough, to halve or quarter player damage, as if that was really necessary for single-players.

People say enemies have 4x the HP effectively, so what if we changed one of these options so that the player just did 4x the damage? I don't even know why there are options to make characters weaker when you could just bring less powerful Gear or literally unequip your levels. Scaling down is endlessly modular, scaling up not so much-- which is also what makes magic a joke, since its resource game scales very poorly against acts of attrition.

**Comment by vitor251093** [comment]
Usually, when I want to create a new AR Code, I use Desmume. It has useful features for that. I'm not sure if it would be easy to find the enemy stats with that method, but if you know some values it may be easier 

Currently, it's possible to replace our built in cheat codes with new ones, but not to combine them with new ones (for now).

Btw, that is one big issue title 🤣

**Comment by sandwichwater** [comment]
enemy health values are hardcoded into the game , youd have to do a full rom hack in order to change them

you can change how much damage you via ar code do but it doesnt scale , if you change your damage output value to do , for example , 50 points of damage , thats 50 for _everything_ all the time : normal combos , finishers , magic , jolting , etc . it doesnt scale with keyblade or level , meaning even at lvl 100 with the strongest keyblade with max strength and crit bonus youll _always_ do only 50 points of damage with every type of attack . youd have to set your damage output very high to have any effect on stronger enemies , but unfortunately that means youll one shot most other enemies

your best bet would be somehow hacking either the arm9 , arm7 , or overlays as thats where theyre most likely stored , ive tried every other file in every other directory and none of them seem to have any effect ...

**Comment by sandwichwater** [comment]
thinking about it again maybe i should add my (scuffed) critical mode codes as an alternative option in the future

**Comment by vitor251093** [comment]
Since the cheats thing will be sorted by #104, I will close this issue, and the other things are currently beyond our scope, I will close this issue
