### ISSUE TITLE
Massive screen freak out when sora is in the bottom screen

### ISSUE THREAD

**Issue by TheRealMatthew4** [vitor251093/KHDays_FM#48]
mission 39 https://youtu.be/UpcoxWvhNKA it looks much worse in person running on Linux pop os  22.04
i happened before in the game but never during an entire boss fight usally just for a cutsceane

**Comment by TheRealMatthew4** [comment]
I managed to beat the boss and right at the end the low-quality version takes over the screen than immediately goes back to HD after you leave the colosseum

**Comment by sandwichwater** [comment]
this is a known display mode issue , thankfully it doesnt happen during gameplay very often and only happens during a boss once

**Comment by vitor251093** [comment]
For now, I've solved the flicking effect by keeping both screens since by side all the time.

It still isn't ideal, but at least it shouldn't be seizure inducing.

Any attempt to give more focus to the first screen resulted in glitches. It seems that, during those double 3D scenes, melonDS OpenGL rendered only increased the scale on one of each two frames.

**Comment by vitor251093** [comment]
This issue will be further analysed in #23
