### ISSUE TITLE
Multiplayer mission result game scene isn't supported yet

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#62]
https://github.com/vitor251093/KHDays_FM/assets/70611518/31964106-6029-48b1-95ae-675924ce7794

**Comment by sandwichwater** [comment]
i figure id mention that the red segmented screen off to the left was a part of the ui update (has since been fixed) and was the bug i was mentioning , but the rapid flashing and double displays happen during story scenes as well making it hard to read dialogue and see whats happening on screen which can be detrimental during bosses it happens on

**Comment by vitor251093** [comment]
I see. Still, ideally, during the multiplayer result screen, the screens should be one on top of the other, so we can replicate the same effect they would have on the DS screen. This is what I will try to achieve by creating a new game scene for it.

**Comment by sandwichwater** [comment]
sounds good👍 thats probably the best way to go about it

**Comment by vitor251093** [comment]
This issue will be split in a bug and an enhancement.

The bug will deal with the detection of the scene, and showing both screens, one on top of the other.

The enhancement will deal with a more proper display for that scene, filling the gap between the two screens and filling the rest of the result room screen.

**Comment by vitor251093** [comment]
Fixed the last instances of scene detection where this was failing. Improvements in the look of that scene will be done in #72
