### ISSUE TITLE
Proper handle scenes with 3D on both screens (Sora flashbacks)

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#71]
Instead of showing both screens side by side, that kind of scene should be handled on a more proper manner.

More details in #23

**Comment by JordanAClark** [comment]
Hey, sorry if this is in the wrong spot, I am not used to how github works. I just did mission 41 Eliminate the Morning Star. In this mission the game (as in intended behavior) only shows the 3D Sora flashback on the bottom screen for the first few seconds of the fight with the Morning Star. The problem is that after that happens in Melon Mix, it stays in the dual screen view for the rest of the battle, even though the bottom screen is just black. Ideally when the bottom screen goes black it should just revert to the top screen only view.

**Comment by vitor251093** [comment]
@JordanAClark yeah, this is part of what this issue intends to deal with.

It shows both screens because, despite the fact that the bottom screen is black, the 3D is still being rendered on the bottom screen; it's just the brightness that is disabled, per say. And scenes with 3D on both screens are still not properly supported.

Reverting to the top screen isn't that simple because of the way melonDS handles 3D on both screens in the OpenGL renderer.

**Comment by JordanAClark** [comment]
Ah ok. Thought I had a case outside what had been discussed, but sounds like it has been considered and is being worked on

**Comment by vitor251093** [comment]
For now, that is issue is considered as solved starting from v0.3.0. If any issue is encountered is any specific scene, specific bugs will be created to handle them specifically
