### ISSUE TITLE
title menu shows incorrect emphasis when quitting to the menu

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#76]
seems to revert back to normal when a single screen override happens

https://github.com/vitor251093/KHDays_FM/assets/70611518/11799040-3120-4e46-ba85-9f65f0c1394f

**Comment by vitor251093** [comment]
I've just made a change that should fix this issue. Although, since the "Unknown (2D)" scene is still triggered at multiple points, it's possible that this fix may produce other bugs, although, I hope not.

I've checked a bunch of other scenarios though, and all of them seemed fine.

**Comment by sandwichwater** [comment]
ill go through as well to check and then report back

**Comment by sandwichwater** [comment]
ive only found two minor bugs , first is with prerendered cutscenes , with them going black at incorrect points . though its doesnt prevent gameplay and cutscene replacement will eventually fix all the issues related to prerendered cutscenes (hopefully) 

the second issue is one weve faced multiple times and will probably continue to curse us lol , the roxas inner monologue keeps disappearing . it doesnt seem consistent though ... the second time it appears it just displays a black screen but every other time it appears it displays properly . very bizarre , not sure whats so special about the second occurence of it  that makes it not display properly

**Comment by vitor251093** [comment]
> first is with prerendered cutscenes , with them going black at incorrect points . though its doesnt prevent gameplay and cutscene replacement will eventually fix all the issues related to prerendered cutscenes (hopefully)

Since we still don't know how that replacement is gonna work, it would be better to fix that just in case. Is there any cutscene where this happens consistently?

> the second issue is one weve faced multiple times and will probably continue to curse us lol , the roxas inner monologue keeps disappearing . it doesnt seem consistent though ... the second time it appears it just displays a black screen but every other time it appears it displays properly . very bizarre , not sure whats so special about the second occurence of it that makes it not display properly

It should be reproducible somehow. In which day have you seen this issue?

Also, were those issues there before today's bug fix? Or are they unrelated?

**Comment by sandwichwater** [comment]
> Is there any cutscene where this happens consistently?

some of them off the top of my head are "the dark margin" , "axel and saix" , and the games opening

> In which day have you seen this issue?

huhm , first time i tested it happened on the monologue right after day 7 but i just went through all the tutorial days containing the monologues and they all displayed fine . mustve been a false alarm , my bad

> Also, were those issues there before today's bug fix? Or are they unrelated?

that im unsure about now that you mention it , i just went through about half the games scenarios and discovered them tonight , it could be that they existed but i just never thought to check those situations in specific

> Since we still don't know how that replacement is gonna work

an idea , would it be possible to have a folder full of hd cutscenes and have a function or shader that calls those from the folder to play the video over the emulator when a prerendered cutscene is playing ¿ it would be a sortof hacky way of doing replacement seeing as it would just be playing video while the original game plays underneathe , but it might work

**Comment by vitor251093** [comment]
> prerendered cutscenes , with them going black at incorrect points

> some of them off the top of my head are "the dark margin" , "axel and saix" , and the games opening

I will check that out next Monday.

> huhm , first time i tested it happened on the monologue right after day 7 but i just went through all the tutorial days containing the monologues and they all displayed fine . mustve been a false alarm , my bad

No worries. It's one problem less then xD

> that im unsure about now that you mention it , i just went through about half the games scenarios and discovered them tonight , it could be that they existed but i just never thought to check those situations in specific

I hope they are not connected to the minimap then xD it took way too long to make it actually look good

> an idea , would it be possible to have a folder full of hd cutscenes and have a function or shader that calls those from the folder to play the video over the emulator when a prerendered cutscene is playing ¿ it would be a sortof hacky way of doing replacement seeing as it would just be playing video while the original game plays underneathe , but it might work

While that makes sense conceptually, I don't think it's possible to load a file from a shader. The shader can only perform calculations with whatever is given to it. Otherwise, it can't even access functions from the application itself.

With that being said, if I can provide the correct HD cutscene frame to it, it should be capable of replacing the original cutscene with it, but that leads us to the major problem: how to detect _which_ cutscene is playing?

It may be possible to discover that using the same technique I used to figure out the memory address of the in-game camera menu option, but I haven't tried that yet.

**Comment by vitor251093** [comment]
> I will check that out next Monday.

Fixed it
